# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Thu Aug 30 03:06:07 2018
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(645, 500)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans Mono")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(968, 650))
        self.centralwidget.setObjectName("centralwidget")
        self.label_img0 = QtWidgets.QLabel(self.centralwidget)
        self.label_img0.setGeometry(QtCore.QRect(0, 0, 320, 240))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_img0.setFont(font)
        self.label_img0.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label_img0.setMouseTracking(True)
        self.label_img0.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_img0.setScaledContents(True)
        self.label_img0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img0.setObjectName("label_img0")
        self.label_img1 = QtWidgets.QLabel(self.centralwidget)
        self.label_img1.setGeometry(QtCore.QRect(325, 0, 320, 240))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_img1.setFont(font)
        self.label_img1.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_img1.setMouseTracking(True)
        self.label_img1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img1.setScaledContents(True)
        self.label_img1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img1.setObjectName("label_img1")
        self.label_img2 = QtWidgets.QLabel(self.centralwidget)
        self.label_img2.setGeometry(QtCore.QRect(0, 245, 320, 240))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_img2.setFont(font)
        self.label_img2.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_img2.setMouseTracking(True)
        self.label_img2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img2.setScaledContents(True)
        self.label_img2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img2.setObjectName("label_img2")
        self.label_img3 = QtWidgets.QLabel(self.centralwidget)
        self.label_img3.setGeometry(QtCore.QRect(325, 245, 320, 240))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.label_img3.sizePolicy().hasHeightForWidth())
        self.label_img3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_img3.setFont(font)
        self.label_img3.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label_img3.setMouseTracking(True)
        self.label_img3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img3.setScaledContents(True)
        self.label_img3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img3.setObjectName("label_img3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 645, 14))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_ctrl = QtWidgets.QMenu(self.menubar)
        self.menu_ctrl.setObjectName("menu_ctrl")
        self.menuinfo = QtWidgets.QMenu(self.menubar)
        self.menuinfo.setObjectName("menuinfo")
        MainWindow.setMenuBar(self.menubar)
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.menuinfo.addAction(self.actionabout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Arducam Rpi Multi Cameras Show"))
        self.label_img0.setText(_translate("MainWindow", "IMG0"))
        self.label_img1.setText(_translate("MainWindow", "IMG1"))
        self.label_img2.setText(_translate("MainWindow", "IMG2"))
        self.label_img3.setText(_translate("MainWindow", "IMG3"))
        self.menu_file.setTitle(_translate("MainWindow", "file"))
        self.menu_ctrl.setTitle(_translate("MainWindow", "ctrl"))
        self.menuinfo.setTitle(_translate("MainWindow", "info"))
        self.actionabout.setText(_translate("MainWindow", "about"))

